//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Mar 27 2019 15:10:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HomeAlertTask.h"

@class _TtC8SWCampus11AppUpgrader;

@interface AppUpgradeTask : HomeAlertTask
{
    _TtC8SWCampus11AppUpgrader *_upgrader;
}

- (void).cxx_destruct;
@property(retain, nonatomic) _TtC8SWCampus11AppUpgrader *upgrader; // @synthesize upgrader=_upgrader;
- (void)execute:(id)arg1;
- (id)init;

@end

